" Plugin 'altercation/vim-colors-solarized.git'
Plugin 'majutsushi/tagbar.git'
Plugin 'leafgarland/typescript-vim'
Plugin 'Lokaltog/vim-easymotion.git'
Plugin 'luochen1990/rainbow'
Plugin 'Raimondi/delimitMate.git'
Plugin 'scrooloose/nerdcommenter.git'
Plugin 'scrooloose/nerdtree.git'
" Plugin 'scrooloose/syntastic.git'
Plugin 'sickill/vim-monokai'
Plugin 'tpope/vim-fugitive.git'
Plugin 'tpope/vim-surround.git'
Plugin 'vim-airline/vim-airline.git'
Plugin 'vim-airline/vim-airline-themes'
