# When needed, set PATH in .zshenv rather than .zshrc so that
# it will be used by both interactive and non-interactive
# shells

# On some systems (macOS, Arch), the PATH should be set
# elsewhere. On macOS, the path_helper utility does it.

# This command might speed up load times on some systems.
#skip_global_compinit=1
