name: 'Test dotfiles install'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Cancel in-progress runs when a newer commit is pushed to the same ref
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Echo branch name
        run: echo "GITHUB_HEAD_REF is $GITHUB_HEAD_REF"
      - name: Test dotfiles installation
        run: DOTFILES_BRANCH=$GITHUB_HEAD_REF bash scripts/install_dotfiles.sh
