name: 'Test dotfiles install'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Echo branch name
        run: echo "GITHUB_HEAD_REF is $GITHUB_HEAD_REF"
      - name: Test dotfiles installation
        run: DOTFILES_BRANCH=$GITHUB_HEAD_REF bash -c scripts/install_dotfiles.sh
